import 'dotenv/config';
import { PrismaClient, PriceType } from '@prisma/client';
import { PrismaNeon } from '@prisma/adapter-neon';

const prisma = new PrismaClient({
  adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL }),
});

const services = [
  {
    slug: 'wig-basic-wash',
    category: 'Wig Care',
    sortOrder: 1,
    name: 'Basic Wig Wash',
    description: 'Sulphate-free cleanse, conditioning and a cool rinse.',
    priceCents: 15000,
    durationMinutes: 45,
    pointsAwarded: 15,
  },
  {
    slug: 'wig-moisture-treatment',
    category: 'Wig Care',
    sortOrder: 2,
    name: 'Moisture Treatment',
    description: 'A deep moisture mask that restores softness to dry or ageing hair.',
    priceCents: 20000,
    durationMinutes: 60,
    pointsAwarded: 20,
  },
  {
    slug: 'wig-keratin-treatment',
    category: 'Wig Care',
    sortOrder: 3,
    name: 'Keratin Treatment',
    description: 'A smoothing keratin service that tames frizz for a sleek finish.',
    priceCents: 25000,
    durationMinutes: 90,
    pointsAwarded: 25,
  },

  {
    slug: 'wig-customization-basic',
    category: 'Customization & Styling',
    sortOrder: 1,
    name: 'Basic Customization',
    description: 'Plucking and baby hairs for a softer, natural hairline.',
    priceCents: 20000,
    durationMinutes: 60,
    pointsAwarded: 20,
  },
  {
    slug: 'wig-customization-advanced',
    category: 'Customization & Styling',
    sortOrder: 2,
    name: 'Advanced Customization',
    description: 'Plucking, baby hairs and a lace tint matched to your scalp.',
    priceCents: 25000,
    durationMinutes: 90,
    pointsAwarded: 25,
  },
  {
    slug: 'wig-customization-full',
    category: 'Customization & Styling',
    sortOrder: 3,
    name: 'Full Customization',
    description: 'Plucking, tint, baby hairs and styling for a finished install.',
    priceCents: 30000,
    priceType: PriceType.RANGE,
    priceMaxCents: 35000,
    durationMinutes: 120,
    pointsAwarded: 30,
  },
  {
    slug: 'wig-customization-glueless',
    category: 'Customization & Styling',
    sortOrder: 4,
    name: 'Glueless Customization',
    description: 'Full customization plus elastic, band and adjustments for a secure glueless fit.',
    priceCents: 35000,
    priceType: PriceType.RANGE,
    priceMaxCents: 45000,
    durationMinutes: 150,
    pointsAwarded: 35,
  },
  {
    slug: 'wig-styling',
    category: 'Customization & Styling',
    sortOrder: 5,
    name: 'Wig Styling',
    description: 'Curls or straightening to restyle a unit.',
    priceCents: 10000,
    priceType: PriceType.FROM,
    durationMinutes: 45,
    pointsAwarded: 10,
  },
  {
    slug: 'wig-colouring',
    category: 'Customization & Styling',
    sortOrder: 6,
    name: 'Colouring',
    description: 'Custom colour, priced on the unit and the look.',
    priceCents: 25000,
    priceType: PriceType.FROM,
    durationMinutes: 120,
    pointsAwarded: 25,
  },
  {
    slug: 'wig-frontal-replacement',
    category: 'Customization & Styling',
    sortOrder: 7,
    name: 'Frontal / Closure Replacement',
    description: 'Replace or customize a frontal or closure.',
    priceCents: 35000,
    priceType: PriceType.FROM,
    durationMinutes: 120,
    pointsAwarded: 35,
  },

  {
    slug: 'nails-gelx-short',
    category: 'Nails',
    sortOrder: 1,
    name: 'Gel-X Short (plain)',
    description: 'Short Gel-X extensions, plain and ready for colour.',
    priceCents: 25000,
    durationMinutes: 75,
    pointsAwarded: 25,
  },
  {
    slug: 'nails-gelx-medium',
    category: 'Nails',
    sortOrder: 2,
    name: 'Gel-X Medium (plain)',
    description: 'Medium-length Gel-X extensions, plain.',
    priceCents: 28000,
    durationMinutes: 90,
    pointsAwarded: 28,
  },
  {
    slug: 'nails-gelx-long',
    category: 'Nails',
    sortOrder: 3,
    name: 'Gel-X Long (plain)',
    description: 'Long Gel-X extensions, plain.',
    priceCents: 32000,
    durationMinutes: 105,
    pointsAwarded: 32,
  },
  {
    slug: 'nails-gelx-refill',
    category: 'Nails',
    sortOrder: 4,
    name: 'Gel-X Refill / Maintenance',
    description: 'Rebalance and maintain an existing Gel-X set.',
    priceCents: 22000,
    priceType: PriceType.RANGE,
    priceMaxCents: 28000,
    durationMinutes: 75,
    pointsAwarded: 22,
  },
  {
    slug: 'nails-soakoff-alora',
    category: 'Nails',
    sortOrder: 5,
    name: 'Soak-off (Alora set)',
    description: 'Gentle removal of a set applied at Alora.',
    priceCents: 5000,
    durationMinutes: 20,
    pointsAwarded: 5,
  },
  {
    slug: 'nails-soakoff-other',
    category: 'Nails',
    sortOrder: 6,
    name: 'Soak-off (other salon)',
    description: 'Gentle removal of a set applied elsewhere.',
    priceCents: 7000,
    durationMinutes: 30,
    pointsAwarded: 7,
  },
  {
    slug: 'nails-repair',
    category: 'Nails',
    sortOrder: 7,
    name: 'Nail Repair (per nail)',
    description: 'Single-nail repair, priced per nail.',
    priceCents: 3000,
    durationMinutes: 15,
    pointsAwarded: 3,
  },

  {
    slug: 'makeup-soft-glam',
    category: 'Makeup',
    sortOrder: 1,
    name: 'Natural / Soft Glam',
    description: 'A natural, everyday soft glam. Lashes included.',
    priceCents: 30000,
    durationMinutes: 60,
    pointsAwarded: 30,
  },
  {
    slug: 'makeup-full-glam',
    category: 'Makeup',
    sortOrder: 2,
    name: 'Full Glam',
    description: 'A sculpted full glam for events and shoots. Lashes included.',
    priceCents: 35000,
    durationMinutes: 75,
    pointsAwarded: 35,
  },
  {
    slug: 'makeup-bridal',
    category: 'Makeup',
    sortOrder: 3,
    name: 'Bridal Makeup',
    description: 'Long-wear bridal makeup, quoted on the look. Lashes included.',
    priceCents: 60000,
    priceType: PriceType.RANGE,
    priceMaxCents: 80000,
    durationMinutes: 120,
    pointsAwarded: 60,
  },
  {
    slug: 'makeup-bridesmaid',
    category: 'Makeup',
    sortOrder: 4,
    name: 'Bridesmaid Makeup',
    description: 'Coordinated bridesmaid makeup. Lashes included.',
    priceCents: 45000,
    priceType: PriceType.RANGE,
    priceMaxCents: 55000,
    durationMinutes: 90,
    pointsAwarded: 45,
  },
  {
    slug: 'makeup-strip-lashes',
    category: 'Makeup',
    sortOrder: 5,
    name: 'Strip Lashes Only',
    description: 'Strip lash application on its own.',
    priceCents: 5000,
    durationMinutes: 15,
    pointsAwarded: 5,
  },
  {
    slug: 'makeup-travel',
    category: 'Makeup',
    sortOrder: 6,
    name: 'Travel / Mobile Makeup',
    description: 'We come to you; travel is quoted by distance.',
    priceCents: 15000,
    priceType: PriceType.FROM,
    durationMinutes: 30,
    pointsAwarded: 15,
  },

  {
    slug: 'matric-hair-makeup',
    category: 'Matric',
    sortOrder: 1,
    name: 'Matric Package (Hair + Makeup)',
    description:
      'Wig customization, installation and styling, plus full glam and lashes, quoted together.',
    priceCents: 85000,
    priceType: PriceType.RANGE,
    priceMaxCents: 100000,
    durationMinutes: 240,
    pointsAwarded: 85,
  },
];

const retiredSlugs = [
  'protective-braids',
  'wig-wash-style',
  'knotless-braids',
  'box-braids',
  'cornrows',
  'fulani-braids',
  'faux-locs',
  'passion-twists',
  'loc-retwist',
  'twist-out',
  'wash-and-go',
  'cut-and-shape',
  'bantu-knots',
  'silk-press',
];

async function main() {
  for (const service of services) {
    await prisma.service.upsert({
      where: { slug: service.slug },
      update: service,
      create: service,
    });
  }
  await prisma.service.updateMany({
    where: { slug: { in: retiredSlugs } },
    data: { active: false },
  });
  console.log(`Seeded ${services.length} services; retired ${retiredSlugs.length}.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
